version: 2
updates:
  - package-ecosystem: "github-actions"
    # NOTE: we run old glibc for Linux builds. Not all action updates may always work.
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      artifacts:
        patterns:
          - "upload-artifact"
          - "download-artifact"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      build-tools:
        patterns:
          - "setuptools"
          - "types-setuptools"
      build-dependencies:
        patterns:
          - "cython"
      linters:
        patterns:
          - "*"
        exclude-patterns:
          - "setuptools"
          - "types-setuptools"
          - "cython"
