name: Test

# for now just try to build it

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!.github/workflows/**'
      - '.github/workflows/test.yaml'
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!.github/workflows/**'
      - '.github/workflows/test.yaml'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      #fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python:
          - {version: '3.10'}
          - {version: '3.11.2'}
          - {version: '3.12'}
          #- {version: '3.13'}
          - {version: '3.14'}
        include:
          - python: {version: '3.10'}  # old
            os: windows-latest
          - python: {version: '3.13'}  # current
            os: windows-latest
          - python: {version: '3.13'}  # current
            os: macos-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        submodules: 'recursive'
    - name: Set up Python ${{ matrix.python.version }}
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
      with:
        python-version: ${{ matrix.python.version }}
    - name: Set up dotnet
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309
      with:
        dotnet-version: '10'
    - name: Build
      run: |
        pip wheel . -v
    - name: Test install wheel
      shell: bash
      run: |
        pip install *.whl
        python -c "import pysomr; print(pysomr)"
